import assert from 'node:assert/strict';
import {examDurationSeconds,examDeadlineMs,submissionTiming} from '../src/domain/exam-clock.js';
import {duplicateExam,detachLockedDraftQuestions} from '../src/domain/exams.js';
import {updateQuestion} from '../src/domain/questions.js';
import {submittedHtml,unansweredExamQuestions} from '../src/views/student.js';
const exam={sections:[{timeMinutes:10},{timeMinutes:20}]};
const attempt={startedAt:'2026-10-10T00:00:00Z'};
assert.equal(examDurationSeconds(exam),1800);
const skillTimed={settings:{skillSettings:{Nghe:{timeMinutes:20},Đọc:{timeMinutes:25},Viết:{timeMinutes:20}}},sections:[{skill:'Nghe',timeMinutes:20},{skill:'Nghe',timeMinutes:20},{skill:'Nghe',timeMinutes:20},{skill:'Đọc',timeMinutes:25},{skill:'Đọc',timeMinutes:25},{skill:'Viết',timeMinutes:20},{skill:'Viết',timeMinutes:20}]};
assert.equal(examDurationSeconds(skillTimed),65*60);
assert.equal(examDeadlineMs(attempt,skillTimed),Date.parse('2026-10-10T01:05:00Z'));
assert.equal(examDeadlineMs(attempt,exam),Date.parse('2026-10-10T00:30:00Z'));
assert.equal(submissionTiming(attempt,exam,Date.parse('2026-10-10T00:10:00Z')).durationSeconds,600);
assert.deepEqual(submissionTiming(attempt,exam,Date.parse('2026-10-10T00:40:00Z')),{timedOut:true,durationSeconds:1800,submittedAt:'2026-10-10T00:30:00.000Z'});
assert.ok(submittedHtml({durationSeconds:65}).includes('Thời gian làm bài: <strong>1 phút 5 giây</strong>'));
assert.deepEqual(unansweredExamQuestions({sections:[{id:'s',questionIds:['ex','a','b','oral']}]},[{id:'ex',example:true},{id:'a',type:'single'},{id:'b',type:'single'},{id:'oral',type:'speaking'}],{a:0}),[{id:'b',number:2,sectionId:'s'}]);
const teacher={id:'copy-owner',role:'teacher',name:'Copier'};
const state={exams:[{id:'source',title:'Original',ownerId:'original-owner',status:'published',locked:true,sections:[{id:'s',questionIds:['q']}]}],questions:[{id:'q',ownerId:'original-owner',locked:true,type:'single',choices:['a','b'],correctAnswer:0}],attempts:[],auditLog:[]};
const copy=duplicateExam(state,teacher,'source');
assert.equal(copy.ownerId,teacher.id);
const qid=copy.sections[0].questionIds[0];
assert.notEqual(qid,'q');
assert.equal(state.questions.find(q=>q.id===qid).locked,false);
// Publishing a copy used to re-lock its questions even with no students.
copy.status='published';state.questions.find(q=>q.id===qid).locked=true;
assert.equal(detachLockedDraftQuestions(state,teacher,copy.id),true);
assert.equal(state.questions.find(q=>q.id===copy.sections[0].questionIds[0]).ownerId,teacher.id);
assert.equal(state.questions.find(q=>q.id===copy.sections[0].questionIds[0]).locked,false);
assert.equal(state.questions[0].locked,true);
updateQuestion(state,teacher,copy.sections[0].questionIds[0],{title:'Edited copy'});
assert.equal(state.questions.find(q=>q.id===copy.sections[0].questionIds[0]).title,'Edited copy');
assert.notEqual(state.questions[0].title,'Edited copy');
console.log('Whole exam deadline, elapsed duration and editable published copies passed.');
