import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {promotionTarget,STUDENT_LEVELS,normalizeStudentLevel} from '../src/domain/student-profile.js';
import {resultSummary} from '../src/domain/result-summary.js';
import {studentExamCardHtml,studentHomeHtml} from '../src/views/student.js';
import {resultSummaryHtml} from '../src/views/result-summary.js';
import {studentProfileCardHtml,studentShareText} from '../src/views/student-profile-card.js';
import {examAccessFormHtml} from '../src/views/exam-access.js';
import {classFormHtml,classesHtml} from '../src/views/classes.js';

assert.equal(STUDENT_LEVELS.length,6);
assert.equal(normalizeStudentLevel('A1.2'),'A1');
assert.equal(normalizeStudentLevel('A1x2'),null);
assert.equal(promotionTarget('A1','A1',true),'A1');
assert.equal(promotionTarget('B2','A1',true),'A1');
const classTeachers=[{id:'t1',name:'Cô Lan',role:'teacher',picture:'https://example.com/lan.jpg'},{id:'t2',name:'Cô Mai',role:'teacher'},{id:'s',name:'Student',role:'student'}];
const classItem={id:'c',code:'A1-01',description:'Lớp <mới>',teacherIds:['t1','t2']};
const classForm=classFormHtml(classItem,classTeachers);
assert.ok(classForm.includes('name="description"'));
assert.equal((classForm.match(/ checked/g)||[]).length,2);
assert.ok(classForm.includes('lan.jpg'));
assert.ok(!classForm.includes('value="s"'));
assert.ok(classesHtml({data:{classes:[classItem],users:classTeachers}}).includes('Lớp &lt;mới&gt;'));
const settingsHtml=examAccessFormHtml({title:'<Exam>',provider:'GOETHE',level:'A1',hidden:true,learningLevel:'A1.2'});
assert.ok(settingsHtml.includes('&lt;Exam&gt;'));
for(const label of ['Quyền truy cập','Trình độ','Mã thi','Lưu thay đổi','Tạo mã'])assert.ok(settingsHtml.includes(label));
assert.ok(settingsHtml.includes('data-settings-status'));
assert.ok(settingsHtml.includes('data-code-status'));
assert.ok(settingsHtml.includes('access-level-row'));
const controlCss=readFileSync(new URL('../styles.css',import.meta.url),'utf8');
for(const selector of ['.profile-form select','.grade-filters select','.exam-filter select','.access-code-create input'])assert.ok(controlCss.includes(selector));
for(const file of ['builder','admin']){
  const source=readFileSync(new URL(`../src/views/${file}.js`,import.meta.url),'utf8');
  assert.match(source,/class="icon-btn" title="Cài đặt đề" aria-label="Cài đặt đề" data-action="exam-access-settings"/);
  assert.ok(!source.includes('>Cài đặt đề</button>'));
}
assert.equal(promotionTarget('A1.1','B1.1',true),'B1');
assert.equal(promotionTarget('A1.1','B1.1',false),null);
assert.equal(promotionTarget('B2.1','A1.1',true),'A1');
assert.equal(promotionTarget('C2.2','C2.2',true),'C2');
assert.equal(promotionTarget('C2.1','C2.2',true),'C2');
assert.equal(promotionTarget('A1.1',null,true),null);
const exam={id:'e',provider:'TELC',level:'B1',learningLevel:'B1.1',status:'published',title:'Exam',sections:[]};
const questions=[];
for(const [skill,max] of Object.entries({reading:75,grammar:30,listening:75,writing:45})){
  exam.sections.push({id:skill,name:skill,skillKey:skill,timeMinutes:10,questionIds:[skill]});
  questions.push({id:skill,maxScore:max});
}
const marks={scoringVersion:2,sectionScores:{reading:75,grammar:30,listening:30,writing:0},manualScores:{},oralScore:45,oralMax:75};
assert.equal(resultSummary(exam,questions,marks).passed,true);
assert.equal(resultSummary(exam,questions,{...marks,oralScore:44.5}).passed,false);
assert.equal(resultSummary(exam,questions,{...marks,oralScore:null}).complete,false);
assert.ok(resultSummaryHtml(resultSummary(exam,questions,marks)).includes('135/225'));
const data={exams:[exam],questions,attempts:[],users:[]};
assert.ok(studentExamCardHtml({...exam,hidden:true,hasActiveCodes:true},[],data).includes('Nhập mã'));
assert.ok(studentExamCardHtml({...exam,hidden:true,hasActiveCodes:false},[],data).includes('Không có mã thi'));
assert.ok(!studentExamCardHtml({...exam,hidden:true},[],data).includes('data-action="start"'));
assert.ok(studentHomeHtml({data,user:{id:'s',name:'Student'},levelFilter:'B1.1'}).includes('Nhập mã đề'));
console.log('Access UI, TELC gates, exact exam-level assignment passed.');
const student={id:'s',name:'Lan <script>',level:'B1',classId:'c',picture:'https://example.com/avatar.jpg'};
const profileData={...data,classes:[{id:'c',code:'PRIVATE-CLASS'}]};
const profile=studentProfileCardHtml(profileData,student);
assert.ok(profile.includes('Lan &lt;script&gt;'));
assert.ok(profile.includes('PRIVATE-CLASS'));
assert.ok(profile.includes('B1'));
assert.ok(profile.includes('data-action="share-profile"'));
assert.ok(!studentShareText(profileData,student).includes('PRIVATE-CLASS'));
const home=studentHomeHtml({data:profileData,user:student});
assert.ok(!home.includes('Xin chào'));
assert.ok(!home.includes('Xem toàn bộ kết quả'));
assert.ok(!home.includes('Chọn bài thi để bắt đầu.'));
assert.ok(home.includes('data-exam-provider-filter'));
assert.ok(home.includes('data-exam-level-filter'));
const rosterData={classes:[classItem,{id:'ext',code:'Extend'}],users:[
  {id:'outside',name:'Nguyen & Lan',email:'lan@example.test',role:'student',classId:'ext',level:'A1',confirmationCode:'ABCDE'},
  {id:'inside',name:'Class Student',email:'in@example.test',role:'student',classId:'c',level:'B1'}
]};
const classList=classesHtml({data:rosterData});
assert.ok(classList.includes('data-open-class="c"'));
assert.ok(classList.includes('data-student-search'));
assert.ok(classList.includes('Mã xác nhận'));
assert.ok(classList.includes('ABCDE'));
assert.ok(classList.includes('Nguyen &amp; Lan'));
assert.ok(!classList.includes('Class Student'));
const roster=classesHtml({data:rosterData,classId:'c'});
assert.ok(roster.includes('Class Student'));
assert.ok(!roster.includes('lan@example.test'));
assert.ok(roster.includes('data-class-back'));
assert.ok(studentProfileCardHtml(rosterData,rosterData.users[0]).includes('data-action="class-enrollment"'));
assert.ok(!studentProfileCardHtml(rosterData,rosterData.users[1]).includes('data-action="class-enrollment"'));
console.log('Student profile: real level, class, safe sharing and removed legacy overview passed.');
