import assert from 'node:assert/strict';
import {patientWritingDemo} from '../src/controllers/writing-demo.js';
import {writingFormScore,writingPointLayout,scoreWritingForm,isAutomaticWritingForm,isRequiredWritingField,addWritingRow,removeWritingRow,publicWritingRows} from '../src/domain/writing-form.js';
import {writingFormEditor,writingFormDisplay,writingSubmission} from '../src/ui/writing-form.js';
import {createQuestion,updateQuestion,getQuestionChoiceError} from '../src/domain/questions.js';
import {validateExamForPublish} from '../src/domain/exams.js';
import {seedState} from '../src/seed.js';

const demo=patientWritingDemo(),q={id:'patient',...demo.question};
const legacyForm={id:'legacy-form',code:'Q-0580',type:'single',title:'Form',writingFormVersion:1,choices:[],rubric:[{type:'choice',label:'Zahlungsweise',options:['monatlich','vierteljährlich','halbjährlich'],correctIndex:1,maxScore:1},{type:'signature',value:'Kristina Pinnow',maxScore:0}]};
const formExam={title:'A1',sections:[{name:'Viết 1',timeMinutes:20,questionIds:[legacyForm.id]}]};
assert.equal(getQuestionChoiceError(legacyForm),'');
assert.deepEqual(validateExamForPublish({questions:[legacyForm]},formExam),[]);
assert.equal(getQuestionChoiceError({rubric:legacyForm.rubric},legacyForm),'');
assert.match(getQuestionChoiceError({...legacyForm,rubric:[{...legacyForm.rubric[0],options:['Only one']}]}),/Ô 1.*2 lựa chọn/);
assert.match(getQuestionChoiceError({...legacyForm,rubric:[{...legacyForm.rubric[0],correctIndex:8}]}),/Ô 1.*đáp án đúng/);
assert.match(getQuestionChoiceError({type:'single',choices:[],correctAnswer:0}),/2 lựa chọn/);
assert.equal(getQuestionChoiceError({...legacyForm,rubric:[{type:'choice',hidden:true,options:[]}]}),'');
assert.equal(isAutomaticWritingForm({provider:'GOETHE',level:'A1'},{questionProfile:{layout:'form-fields'}},{writingFormVersion:1}),true);
assert.equal(isAutomaticWritingForm({provider:'GOETHE',level:'A1'},{questionProfile:{layout:'free-response'}},{writingFormVersion:1}),false);
assert.equal(scoreWritingForm([{type:'text',answers:'Ja|Jawohl',maxScore:.33},{type:'text',answers:'Berlin',maxScore:.33},{type:'text',answers:'Morgen',maxScore:.33}],{0:' jawohl ',1:'BERLIN',2:'morgen'}),1);
assert.equal(scoreWritingForm([{type:'choice',options:['Ja','Nein'],correctIndex:1,maxScore:1},{type:'choice',options:['Ja','Nein'],correctIndex:null,maxScore:1}],{0:'Nein',1:'Ja'}),1);
assert.equal(isRequiredWritingField({type:'text',maxScore:0}),false);
assert.equal(isRequiredWritingField({type:'text',maxScore:.5}),true);
const zeroPointRows=publicWritingRows([{type:'text',label:'Familienname',answers:'Rodriguez',maxScore:0},{type:'choice',label:'Anrede',options:['Herr','Frau'],correctIndex:1,maxScore:0}]);
assert.deepEqual(zeroPointRows.map(row=>row.value),['Rodriguez','Frau']);
const zeroPointView=writingFormDisplay({id:'prefilled',rubric:[{type:'text',label:'Familienname',answers:'Rodriguez',maxScore:0}]});
assert.match(zeroPointView,/value="Rodriguez"/);assert.match(zeroPointView,/form-prefilled/);assert.match(zeroPointView,/disabled/);
assert.equal(writingFormScore(q.rubric),12);
const view=writingFormDisplay(q);
assert.equal((view.match(/type="text"/g)||[]).length,12);
for(let i=0;i<12;i++)assert.equal((view.match(new RegExp(`class="form-point">\\(${i}\\)`,'g'))||[]).length,1);
assert.ok(!view.includes('20969'));assert.ok(!view.includes('Reiseleiter'));
assert.ok(!view.includes('seit gestern'));
assert.ok(writingFormDisplay(q,{7:'Hamburg'}).includes('value="Hamburg"'));
const submission=writingSubmission(q,{7:'Hamburg',8:'<script>'});
assert.ok(submission.includes('Hamburg'));assert.ok(submission.includes('Tham khảo: Reiseleiter'));
assert.ok(writingSubmission(q,{8:'30'}).includes('Tham khảo: 30 · 30 Jahre'));
assert.ok(submission.includes('&lt;script&gt;'));assert.ok(!submission.includes('[object Object]'));
assert.equal((view.match(/class="form-label">Straße, Hausnummer:/g)||[]).length,1);
const editor=writingFormEditor(q);
assert.ok(!editor.includes('<select'));assert.ok(!editor.includes('data-field="audio"'));
assert.ok(editor.includes('<textarea data-rubric-value'));
assert.ok(editor.includes('aria-label="Đáp án đúng"'));
assert.ok(!editor.includes('class="writing-answer-help"'));
assert.ok(!editor.includes('<strong>Ô điền</strong>'));
assert.ok(editor.includes('>Thêm ô trả lời</button>'));
assert.ok(editor.includes('>Thêm chữ ký</button>'));
assert.ok(!editor.includes('>+ Chữ ký mẫu</button>'));
assert.ok(!editor.includes('Đánh dấu ví dụ'));
assert.ok(editor.includes('value="Serjakov, Wladimir"'));
assert.ok(editor.includes('đáp án 1|đáp án 2|đáp án 3'));
assert.ok(!view.includes('30 Jahre'));
const extra={...q,rubric:[{type:'choice',label:'Kurszeit',options:['9–12','13–16','17–20'],correctIndex:1,maxScore:1},{type:'image',imageUrl:'/logo.png',maxScore:0}]};
assert.equal((writingFormDisplay(extra).match(/type="radio"/g)||[]).length,3);
assert.ok(writingFormEditor(extra).includes('type="file" data-rubric-image'));
const compact=writingFormEditor({...q,rubric:[{type:'note',value:'Adresse:'},{type:'signature',label:'Unterschrift:',value:'Wladimir'},{type:'truefalse',label:'Roberto will Jasmin anrufen.',maxScore:1},{type:'image'}]});
assert.ok(!compact.includes('<strong>Đoạn hướng dẫn</strong>'));
assert.ok(!compact.includes('Mô tả ảnh'));
assert.ok(!compact.includes('Chữ ký mẫu'));
assert.ok(compact.includes('<strong>Chữ ký</strong>'));
assert.ok(compact.includes('data-rubric-label')&&compact.includes('data-rubric-correct'));
assert.ok(compact.includes('value="Richtig"')&&compact.includes('value="Falsch"'));
const pub=publicWritingRows([...q.rubric,...extra.rubric]);
assert.ok(pub.every(row=>!('answers' in row)&&!('correctIndex' in row)));
assert.ok(!JSON.stringify(pub).includes('Serjakov, Wladimir'));assert.ok(!JSON.stringify(pub).includes('Reiseleiter'));
assert.equal(writingFormDisplay({...q,rubric:publicWritingRows(q.rubric)}),view);
let rows=removeWritingRow(q.rubric,7);assert.equal(rows.length,q.rubric.length-1);assert.equal(writingFormScore(rows),11);
rows=removeWritingRow(q.rubric,0);assert.equal(rows.length,q.rubric.length-1);assert.equal(rows[0].label,'Name, Vorname:');assert.equal(writingFormScore(rows),12);
rows=removeWritingRow([{type:'image',imageUrl:'/example.png'}],0);assert.deepEqual(rows,[]);
rows=addWritingRow(rows,'image');assert.equal(rows.length,1);assert.equal(rows[0].hidden,false);
rows=addWritingRow(q.rubric,undefined,0);assert.equal(rows.at(-1).type,'heading');assert.equal(rows.at(-1).hidden,false);
rows=addWritingRow(q.rubric,'choice');assert.equal(rows.at(-1).type,'choice');assert.equal(rows.length,q.rubric.length+1);
for(const [n,score] of [[3,.33],[4,.25],[2,.5]])assert.equal(writingFormScore(Array.from({length:n},()=>({type:'text',maxScore:score}))),1);
for(const [n,score] of [[3,.33],[4,.25],[2,.5]]){
  const rubric=Array.from({length:n*5},()=>({type:'text',maxScore:score}));
  assert.equal(writingFormScore(rubric),5);
  assert.deepEqual(writingPointLayout(rubric).markers,rubric.map((_,i)=>i%n===0?`(${i/n})`:''));
  const html=writingFormDisplay({id:'fractional',rubric});
  assert.equal((html.match(/class="form-point"/g)||[]).length,5);
  assert.ok(html.includes('class="form-point">(4)'));
}
const mixed=[.33,.33,.33,.25,.25,.25,.25,.5,.5,1].map(maxScore=>({type:'text',maxScore}));
mixed.splice(1,0,{type:'text',maxScore:1,hidden:true},{type:'note',maxScore:9});
assert.equal(writingFormScore(mixed),4);
assert.deepEqual(writingPointLayout(mixed).markers.filter(Boolean),['(0)','(1)','(2)','(3)']);
assert.equal(writingFormScore([{type:'text',maxScore:.98}]),.98);
const state=structuredClone(seedState),teacher=state.users.find(u=>u.role==='teacher');
const saved=createQuestion(state,teacher,demo.question);
for(let n=0;n<4;n++){updateQuestion(state,teacher,saved.id,{rubric:saved.rubric,maxScore:100});assert.equal(saved.maxScore,12);}
updateQuestion(state,teacher,saved.id,{rubric:removeWritingRow(saved.rubric,7)});assert.equal(saved.maxScore,11);
console.log('Writing form: demo, distinct editors, privacy, fractional scores, repeated saves, add/remove passed.');
