import {ATTEMPT_STATUS,byId} from '../core.js';
import {esc,fmtDate,statusText,typeLabel} from '../ui/format.js';

export function questionModalHtml(q=null){
  const edit=Boolean(q);
  return `<div class="hop-chon" id="modal"><div class="noi-hop"><div class="dau-hop"><div><div class="nhan-muc">${edit?'CHỈNH SỬA CÂU HỎI':'TẠO CÂU HỎI'}</div><h2>${edit?esc(q.title):'Câu hỏi mới'}</h2></div><button class="nut nho" data-action="close-modal">×</button></div><div class="cai-dat"><label>Trình độ</label><select id="qLevel"><option ${q?.level==='B1'?'selected':''}>B1</option><option ${q?.level==='B2'?'selected':''}>B2</option></select><label>Kỹ năng</label><select id="qSkill">${['Đọc hiểu','Ngữ pháp','Nghe hiểu','Viết','Nói'].map(x=>`<option ${q?.skill===x?'selected':''}>${x}</option>`).join('')}</select><label>Phần</label><input id="qPart" value="${esc(q?.part||'Phần 1')}"><label>Loại câu</label><select id="qType">${[['single','Một đáp án'],['truefalse','Đúng / Sai'],['matching','Ghép nội dung'],['cloze','Điền từ'],['writing','Viết'],['speaking','Nói']].map(([v,l])=>`<option value="${v}" ${q?.type===v?'selected':''}>${l}</option>`).join('')}</select><label>Tiêu đề nội bộ</label><input id="qTitle" value="${esc(q?.title||'')}"><label>Hướng dẫn cho học viên</label><input id="qInstruction" value="${esc(q?.instruction||'')}"><label>Nội dung câu hỏi</label><textarea id="qPrompt">${esc(q?.prompt||'')}</textarea><div id="choiceFields"><label>Đáp án lựa chọn (mỗi dòng một đáp án)</label><textarea id="qChoices">${esc((q?.choices||[]).join('\n'))}</textarea><label>Vị trí đáp án đúng (bắt đầu từ 1)</label><input id="qCorrect" type="number" min="1" value="${q?.correctAnswer!=null?Number(q.correctAnswer)+1:1}"></div><div id="matchingFields"><label>Các cặp ghép (mỗi dòng: vế trái | vế phải)</label><textarea id="qPairs">${esc((q?.pairs||[]).map(x=>`${x[0]} | ${x[1]}`).join('\n'))}</textarea></div><label>Điểm tối đa</label><input id="qScore" type="number" min="0" value="${q?.maxScore||1}"><label>Audio hiện tại / URL audio</label><input id="qAudioUrl" value="${esc(q?.audioUrl||'')}"><label>Tải tệp audio</label><input id="qAudioFile" type="file" accept="audio/*"><div id="uploadState" class="phu-de"></div></div><div class="chan-hop"><span class="phu-de">Câu Viết/Nói được chấm thủ công. Câu đã dùng trong đề xuất bản sẽ được khóa nội dung.</span><div class="nhom-nut"><button class="nut" data-action="close-modal">Hủy</button><button class="nut chinh" id="saveQuestion">Lưu câu hỏi</button></div></div></div></div>`;
}

export function previewExamModalHtml(ex){
  return `<div class="hop-chon" id="modal"><div class="noi-hop"><div class="dau-hop"><div><div class="nhan-muc">XEM BÀI THI</div><h2>${esc(ex.title)}</h2></div><button class="nut nho" data-action="close-modal">×</button></div>${(ex.sections||[]).map((s,i)=>`<div class="the" style="margin-top:10px"><b>${i+1}. ${esc(s.name)}</b><div class="phu-de">${s.questionIds.length} câu · ${s.timeMinutes} phút</div></div>`).join('')}</div></div>`;
}

export function previewQuestionModalHtml(q){
  return `<div class="hop-chon" id="modal"><div class="noi-hop"><div class="dau-hop"><div><div class="nhan-muc">XEM CÂU HỎI</div><h2>${esc(q.code)} · ${esc(q.title)}</h2></div><button class="nut nho" data-action="close-modal">×</button></div><div class="the" style="margin-top:14px"><div class="phu-de">${esc(q.level)} · ${esc(q.skill)} · ${typeLabel(q.type)}</div><p>${esc(q.instruction||'')}</p><div class="bai-lam">${esc(q.prompt||'')}</div></div></div></div>`;
}

export function studentGradeModalHtml({data,studentId}){
  const st=byId(data.users,studentId);
  const attempts=data.attempts.filter(a=>a.studentId===studentId).sort((a,b)=>String(b.startedAt).localeCompare(String(a.startedAt)));
  return `<div class="hop-chon" id="modal"><div class="noi-hop"><div class="dau-hop"><div><div class="nhan-muc">LỊCH SỬ ĐIỂM</div><h2>${esc(st?.name||'Học viên')}</h2></div><button class="nut nho" data-action="close-modal">×</button></div><div class="table-wrap" style="margin-top:14px"><table class="bang"><thead><tr><th>Bài thi</th><th>Lần</th><th>Ngày</th><th>Điểm</th><th>Kết quả</th><th>Trạng thái</th></tr></thead><tbody>${attempts.map(a=>`<tr><td>${esc(a.examTitle)}</td><td>#${a.attemptNo}</td><td>${fmtDate(a.submittedAt||a.startedAt)}</td><td>${a.status===ATTEMPT_STATUS.PUBLISHED?(a.totalScore??'—'):'—'}</td><td>${a.status===ATTEMPT_STATUS.PUBLISHED?esc(a.result||'—'):'—'}</td><td>${statusText(a.status)}</td></tr>`).join('')}</tbody></table></div></div></div>`;
}
