(()=>{
const app=document.getElementById('app');
const toast=document.getElementById('toast');
const S={role:null,view:'login',adminTab:'exams',examStep:0,time:4632,builderSection:0,gradeIndex:0,gradeMode:'best',requestSent:false};
const exams=[
 {id:1,name:'TELC B1 – Đề thi thử 01',level:'B1',attempts:1,best:201,status:'done'},
 {id:2,name:'TELC B1 – Đề thi thử 02',level:'B1',attempts:2,best:218,status:'done'},
 {id:3,name:'TELC B1 – Đề thi thử 03',level:'B1',attempts:0,best:null,status:'new'},
 {id:4,name:'TELC B1 – Đề thi thử 04',level:'B1',attempts:1,best:null,status:'inprogress'}
];
let sections=[
 {name:'Đọc hiểu',sub:'3 phần · 20 câu',time:'90 phút'},
 {name:'Ngữ pháp',sub:'2 phần · 20 câu',time:'90 phút'},
 {name:'Nghe hiểu',sub:'3 phần · âm thanh',time:'30 phút'},
 {name:'Viết',sub:'1 bài viết',time:'30 phút'},
 {name:'Nói',sub:'3 phần nói',time:'15 phút'}
];
let bank=[
 {id:'Q-B1-01',level:'B1',skill:'Đọc',part:'Phần 1',type:'Ghép nội dung',owner:'Cô Lan',uses:4,correct:'50%',title:'Homeoffice und Zusammenarbeit'},
 {id:'Q-B1-02',level:'B1',skill:'Đọc',part:'Phần 3',type:'Ghép hai cột',owner:'Cô Mai',uses:5,correct:'55%',title:'Situationen und Anzeigen'},
 {id:'Q-B1-03',level:'B1',skill:'Ngữ pháp',part:'Phần 1',type:'Điền từ',owner:'Cô Lan',uses:6,correct:'60%',title:'Geschäftsjahr – Lückentext'},
 {id:'Q-B1-04',level:'B1',skill:'Nghe',part:'Phần 2',type:'Đúng / Sai',owner:'Cô Mai',uses:7,correct:'65%',title:'Wochenendreise'},
 {id:'Q-B1-05',level:'B1',skill:'Đọc',part:'Phần 2',type:'Một đáp án',owner:'Cô Lan',uses:8,correct:'70%',title:'Digitalisierung im Alltag'},
 {id:'Q-B1-06',level:'B1',skill:'Đọc',part:'Phần 1',type:'Ghép nội dung',owner:'Cô Mai',uses:9,correct:'75%',title:'Kochsendungen'}
];
const gradeStudents=[
 {name:'Nguyễn Văn A',mail:'nguyena@gmail.com',attempt:'Lần 1',auto:148,writing:33,speaking:null,status:'Chờ chấm'},
 {name:'Trần Minh B',mail:'tranb@gmail.com',attempt:'Lần 2',auto:139,writing:32,speaking:null,status:'Chờ chấm'},
 {name:'Lê Thu C',mail:'lec@gmail.com',attempt:'Lần 3',auto:165,writing:39,speaking:64,status:'Chờ chấm'},
 {name:'Phạm Hà D',mail:'phamd@gmail.com',attempt:'Lần 4',auto:151,writing:34,speaking:null,status:'Đang chấm'},
 {name:'Vũ Hoàng E',mail:'vue@gmail.com',attempt:'Lần 5',auto:142,writing:null,speaking:null,status:'Đang chấm'},
 {name:'Đặng Linh F',mail:'dangf@gmail.com',attempt:'Lần 6',auto:157,writing:null,speaking:null,status:'Đang chấm'}
];
function notify(msg){toast.textContent=msg;toast.classList.remove('an');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.add('an'),2300)}
function header(){return `<header class="dau-trang"><div class="thuong-hieu"><div class="logo">G2G</div><div class="ten-he-thong"><strong>Thi thử tiếng Đức</strong><small>Mô phỏng trải nghiệm thi TELC trên máy tính</small></div></div><span class="nhan-vai-tro">${S.role==='student'?'Học viên':S.role==='teacher'?'Giáo viên':'Quản trị cấp cao'}</span></header>`}
function login(){S.role=null;app.innerHTML=`<main class="trang-dang-nhap"><div class="dang-nhap"><section class="gioi-thieu"><div class="tieu-de-nho">G2G CAREER · THI THỬ</div><h1>Luyện đến khi bước vào phòng thi thật không còn bỡ ngỡ.</h1><p>Môi trường thi thử tiếng Đức B1/B2 tập trung vào trải nghiệm làm bài trên máy tính: bố cục câu hỏi, thời gian, nghe âm thanh, chuyển phần và nộp bài.</p><div class="mo-ta">Đọc hiểu · Ngữ pháp · Nghe hiểu · Viết · Nói</div></section><section class="hop-dang-nhap"><h2>Đăng nhập</h2><p class="mo-ta">Học viên đăng nhập bằng Google. Kết quả và toàn bộ lịch sử các lần thi được lưu theo tài khoản.</p><button class="nut-google" id="loginGoogle"><span class="bieu-tuong-google"></span>Đăng nhập bằng Google</button><button class="lien-ket-phu" id="loginStaff">Đăng nhập dành cho Giáo viên / Quản trị</button><div id="staffChoices" class="dang-nhap-nhan-vien an"><button class="nut" data-role="teacher">Vào với vai trò Giáo viên</button><button class="nut" data-role="master">Vào với vai trò Quản trị cấp cao</button></div><p class="mo-ta" style="margin-top:18px;border-top:1px solid var(--vien);padding-top:14px">Bản thử nghiệm hiện mô phỏng đăng nhập.</p></section></div></main>`;
 document.getElementById('loginGoogle').onclick=()=>{S.role='student';S.view='student';render()};
 document.getElementById('loginStaff').onclick=()=>document.getElementById('staffChoices').classList.toggle('an');
 document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{S.role=b.dataset.role;S.view='admin';S.adminTab=S.role==='master'?'teachers':'exams';render()});
}
function studentHome(){app.innerHTML=header()+`<main class="noi-dung-hoc-vien"><div class="tieu-de-trang"><div><h1>Xin chào, Nguyễn Văn A</h1><div class="mo-ta">Chọn bài thi để bắt đầu.</div></div><button class="nut" id="allResults">Xem toàn bộ kết quả</button></div><section class="tom-tat"><div class="chi-so"><small>Bài thi gần nhất</small><b>TELC B1 – Đề thi thử 02</b><div class="mo-ta" style="margin-top:5px">04/10/2026 · Lần thi #1</div></div><div class="chi-so"><small>Điểm gần nhất</small><strong>218 / 300</strong></div><div class="chi-so"><small>Điểm cao nhất</small><strong>218</strong></div><div class="chi-so"><small>Số lần thi</small><strong>3</strong></div><div class="chi-so"><small>Kết quả</small><strong class="dat">ĐẠT</strong></div></section><h2 style="font-size:20px;margin:0 0 14px">Chọn bài thi</h2><section class="luoi-bai-thi">${exams.map(e=>`<article class="the-bai-thi"><span class="nhan">${e.level} · THI THỬ</span><h3>${e.name}</h3><div class="thong-tin">Đọc + Ngữ pháp 90 phút<br>Nghe khoảng 30 phút · Viết 30 phút</div><div class="trang-thai">${e.status==='inprogress'?'Đang làm dở':e.attempts?`Đã thi ${e.attempts} lần`:'Chưa từng thi'}</div><div class="nhom-nut">${e.status==='inprogress'?`<button class="nut nut-chinh startExam">Tiếp tục</button><button class="nut restartExam">Làm lại từ đầu</button>`:`<button class="nut nut-chinh startExam">${e.attempts?'Thi lại':'Bắt đầu thi'}</button>`}</div></article>`).join('')}</section></main>`;
 document.getElementById('allResults').onclick=()=>{S.view='studentResults';render()};
 document.querySelectorAll('.startExam').forEach(b=>b.onclick=()=>{S.view='exam';S.examStep=0;S.time=4632;render()});
 document.querySelectorAll('.restartExam').forEach(b=>b.onclick=()=>notify('Lần thi cũ được lưu là bỏ dở. Một lần thi mới sẽ được bắt đầu.'));
}
function studentResults(){app.innerHTML=header()+`<main class="noi-dung-hoc-vien"><div class="tieu-de-trang"><div><div class="tieu-de-nho">KẾT QUẢ CỦA TÔI</div><h1>Toàn bộ kết quả</h1><div class="mo-ta">Theo dõi tất cả các lần thi đã có điểm, đang chờ chấm hoặc bỏ dở.</div></div><button class="nut" id="backStudent">Quay lại</button></div><div class="thong-ke"><div class="o-thong-ke"><small>Tổng lần thi</small><strong>7</strong></div><div class="o-thong-ke"><small>Đã có điểm</small><strong>5</strong></div><div class="o-thong-ke"><small>Đang chờ chấm</small><strong>1</strong></div><div class="o-thong-ke"><small>Điểm cao nhất</small><strong>226</strong></div></div><div class="bo-loc"><select class="o-lua-chon"><option>Tất cả bài thi</option><option>Đề thi thử 01</option><option>Đề thi thử 02</option></select><select class="o-lua-chon"><option>Tất cả trạng thái</option><option>Đã có điểm</option><option>Đang chờ chấm</option><option>Bỏ dở</option></select></div><div class="bang-wrap"><table class="bang"><thead><tr><th>Bài thi</th><th>Lần</th><th>Ngày</th><th>Đọc</th><th>Ngữ pháp</th><th>Nghe</th><th>Viết</th><th>Nói</th><th>Tổng</th><th>Trạng thái</th><th></th></tr></thead><tbody><tr><td class="ten">TELC B1 – Đề 02</td><td>#1</td><td>04/10/2026</td><td>65</td><td>24</td><td>60</td><td>36</td><td>33</td><td><b>218</b></td><td><span class="trang-thai-nho da-xong">Đã có điểm</span></td><td><button class="nut nut-nho resultDetail">Chi tiết</button></td></tr><tr><td class="ten">TELC B1 – Đề 03</td><td>#1</td><td>05/10/2026</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td><span class="trang-thai-nho cho-cham">Đang chờ chấm</span></td><td></td></tr><tr><td class="ten">TELC B1 – Đề 01</td><td>#2</td><td>01/10/2026</td><td>60</td><td>22</td><td>55</td><td>31</td><td>33</td><td><b>201</b></td><td><span class="trang-thai-nho da-xong">Đã có điểm</span></td><td><button class="nut nut-nho resultDetail">Chi tiết</button></td></tr><tr><td class="ten">TELC B1 – Đề 04</td><td>#1</td><td>03/10/2026</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td><span class="trang-thai-nho da-bo">Bỏ dở</span></td><td></td></tr></tbody></table></div></main>`;
 document.getElementById('backStudent').onclick=()=>{S.view='student';render()};document.querySelectorAll('.resultDetail').forEach(b=>b.onclick=()=>openResultDetail());
}
function openResultDetail(){modal(`<div class="hop-thoai-dau"><div><div class="tieu-de-nho">CHI TIẾT KẾT QUẢ</div><h2>TELC B1 – Đề thi thử 02 · Lần #1</h2></div><button class="nut nut-nho closeModal">Đóng</button></div><div class="thong-ke"><div class="o-thong-ke"><small>Đọc hiểu</small><strong>65/75</strong></div><div class="o-thong-ke"><small>Ngữ pháp</small><strong>24/30</strong></div><div class="o-thong-ke"><small>Nghe hiểu</small><strong>60/75</strong></div><div class="o-thong-ke"><small>Viết</small><strong>36/45</strong></div></div><div class="the"><b>Nhận xét của giáo viên</b><p class="mo-ta">Bài viết có bố cục rõ, xử lý đủ ý. Cần chú ý vị trí động từ ở mệnh đề phụ và dùng liên từ đa dạng hơn.</p></div>`)}
const tasks=[
 {title:'Đọc hiểu · Phần 1',instruction:'Lesen Sie die Texte und wählen Sie jeweils die passende Überschrift.',kind:'read'},
 {title:'Ngữ pháp · Phần 1',instruction:'Wählen Sie für jede Lücke die richtige Lösung.',kind:'grammar'},
 {title:'Nghe hiểu · Phần 2',instruction:'Sie hören den Text. Entscheiden Sie: richtig oder falsch.',kind:'listen'},
 {title:'Viết',instruction:'Schreiben Sie eine E-Mail und bearbeiten Sie alle angegebenen Punkte.',kind:'write'},
 {title:'Nói',instruction:'Bereiten Sie sich auf die mündliche Aufgabe vor.',kind:'speak'}
];
function taskContent(t){if(t.kind==='read')return `<div class="cau-thi"><div class="so-cau">Text 1</div><div class="van-ban">Viele Menschen arbeiten heute teilweise von zu Hause. Für Unternehmen entstehen dadurch neue Möglichkeiten, aber auch neue Regeln für Zusammenarbeit und Kommunikation.</div><select class="o-chon examAnswer"><option value="">Chọn đáp án</option><option>Arbeiten ohne Büro</option><option>Neue Regeln im Team</option></select></div><div class="cau-thi"><div class="so-cau">Text 2</div><div class="van-ban">Kochsendungen im Fernsehen gibt es schon lange. Heute verbinden sie Unterhaltung, Information und Gemeinschaftserlebnis.</div><select class="o-chon examAnswer"><option value="">Chọn đáp án</option><option>Ein Trend, der bleibt</option><option>Nur wer kocht, lernt</option></select></div><div class="cau-thi"><div class="so-cau">Text 3</div><div class="van-ban">Immer mehr Firmen bieten flexible Arbeitszeiten und neue Formen der Zusammenarbeit.</div><select class="o-chon examAnswer"><option value="">Chọn đáp án</option><option>Flexible Arbeitszeiten</option><option>Arbeiten im Ausland</option></select></div>`;
if(t.kind==='grammar')return `<div class="cau-thi"><div class="van-ban" style="line-height:2.2">An alle Kunden,<br><br>zum Start in das neue Geschäftsjahr <select class="o-chon" style="width:auto;margin:0 4px"><option>haben</option><option>hat</option></select> wir uns für Sie etwas Besonderes ausgedacht. Es <select class="o-chon" style="width:auto;margin:0 4px"><option>warten</option><option>wartet</option></select> interessante Preise auf Sie.</div></div>`;
if(t.kind==='listen')return `<div class="the" style="margin-bottom:14px"><b>Âm thanh · Lượt nghe 1/1</b><p class="mo-ta">Trong chế độ thi không thể tua lại hoặc phát lại.</p><button class="nut nut-chinh" id="playAudio">Phát âm thanh</button></div><div class="cau-thi"><div class="van-ban">Die Sprecherin möchte am kommenden Wochenende verreisen.</div><label><input type="radio" name="q1"> Richtig</label> &nbsp;&nbsp; <label><input type="radio" name="q1"> Falsch</label></div>`;
if(t.kind==='write')return `<div class="cau-thi"><div class="van-ban"><b>Aufgabe</b><br>Sie haben an einem Deutschkurs teilgenommen. Schreiben Sie eine E-Mail und bearbeiten Sie alle vier Punkte.</div><textarea class="o-van-ban" style="min-height:300px;margin-top:14px" placeholder="Viết câu trả lời tại đây..."></textarea></div>`;
return `<div class="cau-thi"><div class="van-ban"><b>Aufgabe</b><br>Sprechen Sie über Ihre Erfahrungen und beantworten Sie die Leitfragen.</div><div class="ghi-chu" style="margin-top:14px">Bản thử nghiệm mô phỏng phần Nói bằng màn hình hướng dẫn. Phiên bản dùng thật có thể bổ sung ghi âm.</div></div>`}
function examView(){const t=tasks[S.examStep];app.innerHTML=`<div class="trang-thi"><header class="thanh-thi"><strong>G2G Thi thử</strong><div class="thong-tin-thi"><span>Phần ${S.examStep+1} / ${tasks.length}</span><span class="dong-ho" id="timer">00:00</span></div></header><div class="tien-trinh"><span style="width:${((S.examStep+1)/tasks.length)*100}%"></span></div><main class="noi-dung-thi"><div class="tieu-de-nho">TELC B1 · ĐỀ THI THỬ 03</div><h1>${t.title}</h1><div class="mo-ta">${t.instruction}</div><section class="to-giay-thi">${taskContent(t)}</section><div class="dieu-huong-thi"><button class="nut" id="prevExam" ${S.examStep===0?'disabled':''}>Quay lại</button><div class="bo-dem" id="answeredCount">0 câu đã trả lời</div><button class="nut nut-chinh" id="nextExam">${S.examStep===tasks.length-1?'Nộp bài':'Tiếp theo'}</button></div></main></div>`;updateTimer();document.getElementById('prevExam').onclick=()=>{if(S.examStep>0){S.examStep--;render()}};document.getElementById('nextExam').onclick=()=>{if(S.examStep<tasks.length-1){S.examStep++;render()}else{S.view='submitted';render()}};document.querySelectorAll('.examAnswer').forEach(x=>x.onchange=updateAnswered);const p=document.getElementById('playAudio');if(p)p.onclick=()=>notify('Âm thanh đang phát. Không thể tua lại ở chế độ thi.')}
function updateAnswered(){const n=[...document.querySelectorAll('.examAnswer')].filter(x=>x.value).length;const e=document.getElementById('answeredCount');if(e)e.textContent=n+' câu đã trả lời'}
function updateTimer(){const e=document.getElementById('timer');if(!e)return;const h=Math.floor(S.time/3600),m=Math.floor((S.time%3600)/60),s=S.time%60;e.textContent=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function submitted(){app.innerHTML=header()+`<main class="noi-dung-hoc-vien"><section class="the man-cho"><div class="bieu-tuong">✓</div><div class="tieu-de-nho">ĐÃ NỘP BÀI THÀNH CÔNG</div><h1>TELC B1 – Đề thi thử 03</h1><span class="trang-thai-nho cho-cham">ĐANG CHỜ CHẤM</span><p style="line-height:1.7">Bài thi của bạn đã được ghi nhận. Một số phần cần giáo viên chấm thủ công nên kết quả cuối cùng chưa thể hiển thị ngay.</p><div class="ghi-chu"><b>Khi có kết quả</b><br>Hệ thống sẽ gửi thông báo về email dùng để đăng nhập. Bạn cũng có thể đăng nhập lại để xem điểm và lịch sử các lần thi.</div><button class="nut" id="backAfterSubmit" style="margin-top:18px">Về danh sách bài thi</button></section></main>`;document.getElementById('backAfterSubmit').onclick=()=>{S.view='student';render()}}
function adminShell(){const tabs=S.role==='master'?['teachers','exams','bank','grading','grades','trash']:['exams','bank','grading','grades'];const labels={teachers:'Giáo viên',exams:'Bài thi',bank:'Ngân hàng câu hỏi',grading:'Chấm bài',grades:'Bảng điểm',trash:'Thùng rác'};return header()+`<div class="khung-quan-tri"><aside class="thanh-ben">${tabs.map(t=>`<button class="muc-dieu-huong ${S.adminTab===t?'dang-chon':''}" data-tab="${t}">${labels[t]}</button>`).join('')}</aside><main class="noi-dung-quan-tri" id="adminMain"></main></div>`}
function admin(){app.innerHTML=adminShell();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.adminTab=b.dataset.tab;renderAdminMain()});renderAdminMain()}
function renderAdminMain(){const m=document.getElementById('adminMain');if(!m)return;if(S.adminTab==='exams')m.innerHTML=examList();if(S.adminTab==='bank')m.innerHTML=bankView();if(S.adminTab==='grading')m.innerHTML=gradingView();if(S.adminTab==='grades')m.innerHTML=gradebookView();if(S.adminTab==='teachers')m.innerHTML=teachersView();if(S.adminTab==='trash')m.innerHTML=trashView();bindAdmin()}
function examList(){return `<div class="tieu-de-trang"><div><h1>Tất cả bài thi</h1><div class="mo-ta">Giáo viên xem được bài của nhau; chỉ chủ bài hoặc Quản trị cấp cao được chỉnh sửa/xóa.</div></div><button class="nut nut-chinh" id="newExam">+ Tạo bài thi</button></div><div class="bo-loc"><input class="o-nhap" placeholder="Tìm bài thi..."><select class="o-lua-chon"><option>Tất cả trình độ</option><option>B1</option><option>B2</option></select><select class="o-lua-chon"><option>Tất cả trạng thái</option><option>Bản nháp</option><option>Đã xuất bản</option></select></div><div class="bang-wrap"><table class="bang"><thead><tr><th>Bài thi</th><th>Người tạo</th><th>Cấu trúc</th><th>Trạng thái</th><th>Lượt thi</th><th>Thao tác</th></tr></thead><tbody><tr><td class="ten">TELC B1 – Đề 01</td><td>Cô Lan</td><td>5 phần · 42 câu</td><td><span class="trang-thai-nho da-xong">Đã xuất bản</span></td><td>146</td><td><div class="nhom-nut"><button class="nut nut-nho editExam">Chỉnh sửa</button><button class="nut nut-nho nut-nguy-hiem">Xóa</button></div></td></tr><tr><td class="ten">TELC B1 – Đề 02</td><td>Cô Mai</td><td>5 phần · 41 câu</td><td><span class="trang-thai-nho da-xong">Đã xuất bản</span></td><td>98</td><td><div class="nhom-nut"><button class="nut nut-nho">Xem</button>${S.role==='master'?'<button class="nut nut-nho editExam">Chỉnh sửa</button>':`<button class="nut nut-nho ${S.requestSent?'':'nut-chinh'}" id="requestGrade">${S.requestSent?'Đã xin chấm':'Xin chấm'}</button>`}</div></td></tr></tbody></table></div>`}
function bankView(){return `<div class="tieu-de-trang"><div><h1>Ngân hàng câu hỏi</h1><div class="mo-ta">Kho câu hỏi dùng chung. Chỉ người tạo hoặc Quản trị cấp cao được sửa/xóa.</div></div><button class="nut nut-chinh" id="newQuestion">+ Tạo câu hỏi</button></div><div class="bo-loc"><input class="o-nhap" placeholder="Tìm câu hỏi..."><select class="o-lua-chon"><option>Tất cả trình độ</option><option>B1</option><option>B2</option></select><select class="o-lua-chon"><option>Tất cả kỹ năng</option><option>Đọc</option><option>Ngữ pháp</option><option>Nghe</option><option>Viết</option><option>Nói</option></select><select class="o-lua-chon"><option>Tất cả loại câu</option><option>Một đáp án</option><option>Đúng / Sai</option><option>Ghép nội dung</option><option>Điền từ</option></select></div><div class="bang-wrap"><table class="bang"><thead><tr><th>Mã</th><th>Câu hỏi</th><th>Phân loại</th><th>Người tạo</th><th>Đã dùng</th><th>Tỷ lệ đúng</th><th>Thao tác</th></tr></thead><tbody>${bank.map(q=>`<tr><td>${q.id}</td><td class="ten">${q.title}</td><td>${q.level} · ${q.skill}</td><td>${q.owner}</td><td>${q.uses} đề</td><td>${q.correct}</td><td><div class="nhom-nut"><button class="nut nut-nho previewQuestion" data-id="${q.id}">Xem</button>${S.role==='master'||q.owner==='Cô Lan'?`<button class="nut nut-nho editQuestion" data-id="${q.id}">Sửa</button>`:`<button class="nut nut-nho">Dùng vào đề</button>`}</div></td></tr>`).join('')}</tbody></table></div>`}
function questionBuilder(editId){const q=bank.find(x=>x.id===editId);modal(`<div class="hop-thoai-dau"><div><div class="tieu-de-nho">${q?'CHỈNH SỬA CÂU HỎI':'TẠO CÂU HỎI'}</div><h2>${q?q.id+' · '+q.title:'Tạo câu hỏi mới'}</h2></div><button class="nut nut-nho closeModal">Đóng</button></div><div class="luoi-form"><div class="nhom-form"><label>Trình độ</label><select><option>B1</option><option>B2</option></select></div><div class="nhom-form"><label>Kỹ năng</label><select><option>Đọc hiểu</option><option>Ngữ pháp</option><option>Nghe hiểu</option><option>Viết</option><option>Nói</option></select></div><div class="nhom-form"><label>Phần</label><select><option>Phần 1</option><option>Phần 2</option><option>Phần 3</option></select></div><div class="nhom-form"><label>Độ khó dự kiến</label><select><option>Trung bình</option><option>Dễ</option><option>Khó</option></select></div></div><h3>Loại câu hỏi</h3><div class="loai-cau"><button class="dang-chon"><b>Một đáp án</b><small>Chọn một phương án</small></button><button><b>Đúng / Sai</b><small>Hai lựa chọn</small></button><button><b>Ghép nội dung</b><small>Ghép văn bản</small></button><button><b>Điền từ</b><small>Điền trong đoạn</small></button><button><b>Nghe hiểu</b><small>Âm thanh + câu hỏi</small></button><button><b>Viết</b><small>Bài tự luận</small></button><button><b>Nói</b><small>Ghi âm / chấm tay</small></button></div><h3>Nội dung</h3><div class="nhom-form"><label>Tiêu đề nội bộ</label><input id="qTitle" value="${q?q.title:''}" placeholder="Ví dụ: Geschäftsjahr – Lückentext"></div><div class="nhom-form" style="margin-top:10px"><label>Nội dung câu hỏi / văn bản</label><textarea>Nhập nội dung tiếng Đức tại đây...</textarea></div><h3>Đáp án</h3><div class="the"><label><input type="radio" name="ok" checked> Đáp án A</label><br><br><label><input type="radio" name="ok"> Đáp án B</label><br><br><button class="nut nut-nho">+ Thêm đáp án</button></div><div class="hang-hanh-dong"><button class="nut closeModal">Hủy</button><button class="nut">Lưu nháp</button><button class="nut nut-chinh" id="saveQuestion">Lưu vào ngân hàng</button></div>`);document.getElementById('saveQuestion').onclick=()=>{if(!q){bank.unshift({id:'Q-B1-'+String(bank.length+7).padStart(2,'0'),level:'B1',skill:'Đọc',part:'Phần 1',type:'Một đáp án',owner:'Cô Lan',uses:0,correct:'—',title:document.getElementById('qTitle').value||'Câu hỏi mới'})}closeModal();notify(q?'Đã lưu thay đổi câu hỏi.':'Đã lưu câu hỏi vào Ngân hàng câu hỏi.');renderAdminMain()}}
function previewQuestion(id){const q=bank.find(x=>x.id===id);modal(`<div class="hop-thoai-dau"><div><div class="tieu-de-nho">XEM CÂU HỎI</div><h2>${q.id} · ${q.title}</h2></div><button class="nut nut-nho closeModal">Đóng</button></div><div class="ghi-chu">${q.level} · ${q.skill} · ${q.part} · ${q.type}<br>Người tạo: <b>${q.owner}</b> · Đã dùng trong ${q.uses} đề · Tỷ lệ đúng ${q.correct}</div><div class="the" style="margin-top:14px"><p>Viele Menschen arbeiten heute teilweise von zu Hause. Wählen Sie die passende Antwort.</p><select class="o-chon"><option>Chọn đáp án</option><option>A</option><option>B</option><option>C</option></select></div>`)}
function examBuilder(){S.view='builder';app.innerHTML=header()+`<main class="noi-dung-hoc-vien"><div class="tieu-de-trang"><div><h1>Tạo bài thi mới</h1><div class="mo-ta">Có thể thêm, bớt và sắp xếp lại các phần trong bài thi.</div></div><div class="nhom-nut"><button class="nut" id="backAdmin">Quay lại</button><button class="nut" id="saveDraft">Lưu nháp</button><button class="nut">Xem trước</button><button class="nut nut-chinh" id="publishExam">Xuất bản</button></div></div><div class="bo-cuc-tao-de"><aside class="cot-tao-de"><div class="nhom-form"><label>Tên bài thi</label><input value="TELC B1 – Đề thi thử mới"></div><div class="tieu-de-nho" style="margin-top:14px">CẤU TRÚC BÀI THI</div><div class="danh-sach-phan">${sectionList()}</div><button class="nut nut-nho" id="addSection" style="margin-top:10px">+ Thêm phần</button></aside><section class="cot-tao-de" id="builderQuestions">${builderQuestions()}</section><aside class="cot-tao-de"><div class="tieu-de-nho">CÀI ĐẶT PHẦN</div><div class="nhom-form" style="margin-top:12px"><label>Tên phần</label><input id="sectionName" value="${sections[S.builderSection]?.name||''}"></div><div class="nhom-form" style="margin-top:10px"><label>Thời gian</label><input value="${sections[S.builderSection]?.time||'30 phút'}"></div><label class="chon-tat-ca"><input type="checkbox" checked> Hiển thị đồng hồ</label><label class="chon-tat-ca"><input type="checkbox" checked> Tự nộp khi hết giờ</label><label class="chon-tat-ca"><input type="checkbox"> Trộn thứ tự câu hỏi</label><div class="ghi-chu" style="margin-top:14px">Khi bài đã có học viên thi, nên tạo phiên bản mới trước khi thay đổi cấu trúc.</div></aside></div></main>`;bindBuilder()}
function sectionList(){return sections.map((x,i)=>`<div class="phan-thi ${S.builderSection===i?'dang-chon':''}" data-sec="${i}"><div class="phan-thi-top"><div><b>${i+1}. ${x.name}</b><p>${x.sub}</p></div><div class="nhom-thao-tac"><button class="nut-icon upSection" data-i="${i}" title="Đưa lên">↑</button><button class="nut-icon downSection" data-i="${i}" title="Đưa xuống">↓</button><button class="nut-icon removeSection" data-i="${i}" title="Bỏ phần">×</button></div></div></div>`).join('')}
function builderQuestions(){const sec=sections[S.builderSection]||sections[0];return `<div class="tieu-de-trang"><div><h1 style="font-size:22px">${sec.name}</h1><div class="mo-ta">Thêm câu từ ngân hàng hoặc tạo câu mới.</div></div><div class="nhom-nut"><button class="nut" id="openBank">+ Thêm từ ngân hàng</button><button class="nut nut-chinh" id="createInline">+ Tạo câu mới</button></div></div><div class="danh-sach-cau"><div class="the-cau"><div><b>Q-B1-001 · Homeoffice und Zusammenarbeit</b><p>Đọc hiểu · Phần 1 · 5 điểm</p></div><div class="nhom-thao-tac"><button class="nut nut-nho">Xem</button><button class="nut nut-nho">↑</button><button class="nut nut-nho">↓</button><button class="nut nut-nho nut-nguy-hiem">Bỏ</button></div></div><div class="the-cau"><div><b>Q-B1-002 · Situationen und Anzeigen</b><p>Đọc hiểu · Phần 1 · 5 điểm</p></div><div class="nhom-thao-tac"><button class="nut nut-nho">Xem</button><button class="nut nut-nho">↑</button><button class="nut nut-nho">↓</button><button class="nut nut-nho nut-nguy-hiem">Bỏ</button></div></div></div>`}
function bindBuilder(){document.getElementById('backAdmin').onclick=()=>{S.view='admin';render()};document.getElementById('saveDraft').onclick=()=>notify('Đã lưu bài thi ở trạng thái bản nháp.');document.getElementById('publishExam').onclick=()=>notify('Bài thi đã được xuất bản cho học viên.');document.getElementById('addSection').onclick=()=>{sections.push({name:'Phần mới',sub:'Chưa có câu hỏi',time:'30 phút'});S.builderSection=sections.length-1;examBuilder()};document.getElementById('sectionName').onchange=e=>{sections[S.builderSection].name=e.target.value;notify('Đã đổi tên phần.')};document.querySelectorAll('[data-sec]').forEach(x=>x.onclick=e=>{if(e.target.closest('.nhom-thao-tac'))return;S.builderSection=+x.dataset.sec;examBuilder()});document.querySelectorAll('.upSection').forEach(x=>x.onclick=e=>{e.stopPropagation();const i=+x.dataset.i;if(i>0){[sections[i-1],sections[i]]=[sections[i],sections[i-1]];S.builderSection=i-1;examBuilder()}});document.querySelectorAll('.downSection').forEach(x=>x.onclick=e=>{e.stopPropagation();const i=+x.dataset.i;if(i<sections.length-1){[sections[i+1],sections[i]]=[sections[i],sections[i+1]];S.builderSection=i+1;examBuilder()}});document.querySelectorAll('.removeSection').forEach(x=>x.onclick=e=>{e.stopPropagation();if(sections.length===1){notify('Bài thi phải còn ít nhất một phần.');return}sections.splice(+x.dataset.i,1);S.builderSection=Math.min(S.builderSection,sections.length-1);examBuilder()});document.getElementById('openBank').onclick=bankPicker;document.getElementById('createInline').onclick=()=>questionBuilder()}
function bankPicker(){modal(`<div class="hop-thoai-dau"><div><div class="tieu-de-nho">THÊM TỪ NGÂN HÀNG CÂU HỎI</div><h2>Chọn câu hỏi</h2></div><button class="nut nut-nho closeModal">Đóng</button></div><div class="bo-loc"><input class="o-nhap" placeholder="Tìm câu hỏi..."><select class="o-lua-chon"><option>B1</option><option>B2</option></select><select class="o-lua-chon"><option>Tất cả kỹ năng</option><option>Đọc</option><option>Nghe</option></select></div><label class="chon-tat-ca"><input type="checkbox" id="selectAll"> Chọn tất cả câu hỏi đang hiển thị</label><div class="chon-ngan-hang">${bank.map(q=>`<label><input type="checkbox" class="pickQ"><span><b>${q.id} · ${q.title}</b><br><small>${q.level} · ${q.skill} · ${q.part} · ${q.type}</small></span></label>`).join('')}</div><div class="hang-hanh-dong" style="justify-content:space-between"><span class="mo-ta" id="selectedCount">Đã chọn 0 câu</span><div class="nhom-nut"><button class="nut closeModal">Hủy</button><button class="nut nut-chinh" id="addPicked">Thêm câu đã chọn</button></div></div>`);const all=document.getElementById('selectAll'),items=[...document.querySelectorAll('.pickQ')],count=document.getElementById('selectedCount');const update=()=>{const n=items.filter(x=>x.checked).length;count.textContent='Đã chọn '+n+' câu';all.checked=n===items.length&&n>0;all.indeterminate=n>0&&n<items.length};all.onchange=()=>{items.forEach(x=>x.checked=all.checked);update()};items.forEach(x=>x.onchange=update);document.getElementById('addPicked').onclick=()=>{const n=items.filter(x=>x.checked).length;if(!n){notify('Hãy chọn ít nhất một câu hỏi.');return}closeModal();notify('Đã thêm '+n+' câu hỏi vào phần hiện tại.')}}
function gradingView(){return `<div class="tieu-de-trang"><div><h1>Chấm bài</h1><div class="mo-ta">Các lượt thi đang chờ giáo viên chấm thủ công.</div></div></div><div class="thong-ke" style="grid-template-columns:repeat(3,minmax(0,220px))"><div class="o-thong-ke"><small>Chờ chấm</small><strong>18</strong></div><div class="o-thong-ke"><small>Đang chấm</small><strong>4</strong></div><div class="o-thong-ke"><small>Sẵn sàng công bố</small><strong>7</strong></div></div><div class="phieu-cham"><aside class="danh-sach-cham">${gradeStudents.map((g,i)=>`<div class="hoc-vien-cham ${i===S.gradeIndex?'dang-chon':''}" data-grade="${i}"><b>${g.name}</b><p>TELC B1 – Đề 01 · ${g.attempt}</p><span class="trang-thai-nho ${g.status==='Chờ chấm'?'cho-cham':'dang-cham'}">${g.status}</span></div>`).join('')}</aside><section class="chi-tiet-cham" id="gradingPaper">${gradingPaper()}</section></div>`}
function gradingPaper(){const g=gradeStudents[S.gradeIndex];return `<h2 style="font-size:19px;margin-top:0">${g.name} · Viết</h2><div class="mo-ta" style="margin-bottom:8px">Bài làm của học viên</div><div class="bai-lam">Sehr geehrte Damen und Herren,<br><br>ich schreibe Ihnen, weil ich an Ihrem Deutschkurs teilgenommen habe. Besonders gut gefallen hat mir ...</div><h3 style="font-size:13px;margin-top:16px">Chấm theo tiêu chí</h3><div class="tieu-chi-cham"><span>Hoàn thành yêu cầu</span><input class="diem-tieu-chi rubric" type="number" min="0" max="15" value="12"></div><div class="tieu-chi-cham"><span>Tổ chức diễn đạt</span><input class="diem-tieu-chi rubric" type="number" min="0" max="15" value="11"></div><div class="tieu-chi-cham"><span>Độ chính xác ngôn ngữ</span><input class="diem-tieu-chi rubric" type="number" min="0" max="15" value="10"></div><div class="nhom-form" style="margin-top:12px"><label>Nhận xét</label><textarea style="min-height:70px">Bài viết rõ ý, cần chú ý chia động từ và giới từ.</textarea></div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:14px"><b id="writingTotal">33 / 45</b><div class="nhom-nut"><button class="nut" id="saveGrade">Lưu tạm</button><button class="nut nut-chinh" id="publishGrade">Công bố kết quả</button></div></div>`}
function bindGrading(){document.querySelectorAll('[data-grade]').forEach(x=>x.onclick=()=>{S.gradeIndex=+x.dataset.grade;renderAdminMain()});document.querySelectorAll('.rubric').forEach(x=>x.oninput=()=>{const n=[...document.querySelectorAll('.rubric')].reduce((a,b)=>a+(+b.value||0),0);document.getElementById('writingTotal').textContent=n+' / 45'});const save=document.getElementById('saveGrade');if(save)save.onclick=()=>notify('Đã lưu tạm điểm và nhận xét. Học viên chưa nhìn thấy kết quả.');const pub=document.getElementById('publishGrade');if(pub)pub.onclick=()=>notify('Đã công bố kết quả. Học viên sẽ nhận thông báo qua email.')}
function gradebookView(){return `<div class="tieu-de-trang"><div><h1>Bảng điểm</h1><div class="mo-ta">Theo dõi kết quả, số lần thi và tiến bộ của học viên.</div></div><div class="nhom-nut"><button class="nut" id="exportScores">Xuất tệp</button><select class="o-lua-chon" id="gradeMode"><option value="best" ${S.gradeMode==='best'?'selected':''}>Điểm cao nhất</option><option value="latest" ${S.gradeMode==='latest'?'selected':''}>Điểm gần nhất</option><option value="all" ${S.gradeMode==='all'?'selected':''}>Tất cả lần thi</option></select></div></div><div class="bo-loc"><input class="o-nhap" placeholder="Tìm học viên..."><select class="o-lua-chon"><option>Tất cả bài thi</option><option>TELC B1 – Đề 01</option></select><select class="o-lua-chon"><option>Tất cả trạng thái</option><option>Đạt</option><option>Chờ chấm</option></select></div>${S.gradeMode==='all'?allAttempts():scoreSummary()}`}
function scoreSummary(){return `<div class="bang-wrap"><table class="bang"><thead><tr><th>Học viên</th><th>Đọc</th><th>Ngữ pháp</th><th>Nghe</th><th>Viết</th><th>Nói</th><th>Tổng</th><th>Số lần</th><th>Trạng thái</th><th></th></tr></thead><tbody><tr><td class="ten">Nguyễn Văn A</td><td>65</td><td>24</td><td>60</td><td>36</td><td>57</td><td><b>242</b></td><td>3</td><td class="chu-xanh">Đạt</td><td><button class="nut nut-nho scoreDetail">Chi tiết</button></td></tr><tr><td class="ten">Trần Minh B</td><td>55</td><td>19</td><td>43</td><td>30</td><td>41</td><td><b>188</b></td><td>2</td><td>Chờ chấm</td><td><button class="nut nut-nho scoreDetail">Chi tiết</button></td></tr><tr><td class="ten">Lê Thu C</td><td>72</td><td>26</td><td>69</td><td>41</td><td>63</td><td><b>271</b></td><td>5</td><td class="chu-xanh">Đạt</td><td><button class="nut nut-nho scoreDetail">Chi tiết</button></td></tr><tr><td class="ten">Phạm Hà D</td><td>61</td><td>21</td><td>50</td><td>34</td><td>55</td><td><b>221</b></td><td>4</td><td class="chu-xanh">Đạt</td><td><button class="nut nut-nho scoreDetail">Chi tiết</button></td></tr><tr><td class="ten">Vũ Hoàng E</td><td>48</td><td>17</td><td>45</td><td>—</td><td>—</td><td>—</td><td>1</td><td>Chờ chấm</td><td></td></tr></tbody></table></div>`}
function allAttempts(){return `<div class="bang-wrap"><table class="bang"><thead><tr><th>Học viên</th><th>Bài thi</th><th>Lần</th><th>Ngày thi</th><th>Tổng</th><th>Kết quả</th><th>Người chấm</th><th></th></tr></thead><tbody><tr><td class="ten">Nguyễn Văn A</td><td>Đề 01</td><td>#4</td><td>05/10/2026</td><td>226</td><td class="chu-xanh">Đạt</td><td>Cô Lan</td><td><button class="nut nut-nho scoreDetail">Chi tiết</button></td></tr><tr><td class="ten">Nguyễn Văn A</td><td>Đề 02</td><td>#1</td><td>04/10/2026</td><td>218</td><td class="chu-xanh">Đạt</td><td>Cô Mai</td><td><button class="nut nut-nho scoreDetail">Chi tiết</button></td></tr><tr><td class="ten">Nguyễn Văn A</td><td>Đề 04</td><td>#1</td><td>03/10/2026</td><td>—</td><td>Bỏ dở</td><td>—</td><td></td></tr></tbody></table></div>`}
function scoreDetail(){modal(`<div class="hop-thoai-dau"><div><div class="tieu-de-nho">HỒ SƠ ĐIỂM</div><h2>Nguyễn Văn A</h2><div class="mo-ta">nguyena@gmail.com · 4 lần thi</div></div><button class="nut nut-nho closeModal">Đóng</button></div><div class="thong-ke"><div class="o-thong-ke"><small>Điểm cao nhất</small><strong>226</strong></div><div class="o-thong-ke"><small>Điểm gần nhất</small><strong>226</strong></div><div class="o-thong-ke"><small>Điểm trung bình</small><strong>207</strong></div><div class="o-thong-ke"><small>Xu hướng</small><strong>↗</strong></div></div><h3>Lịch sử các lần thi</h3><div class="bang-wrap"><table class="bang"><thead><tr><th>Lần thi</th><th>Ngày</th><th>Đọc</th><th>Ngữ pháp</th><th>Nghe</th><th>Viết</th><th>Nói</th><th>Tổng</th></tr></thead><tbody><tr><td>#1</td><td>29/09</td><td>51</td><td>18</td><td>48</td><td>29</td><td>38</td><td>184</td></tr><tr><td>#2</td><td>01/10</td><td>60</td><td>22</td><td>55</td><td>31</td><td>33</td><td>201</td></tr><tr><td>#3</td><td>04/10</td><td>65</td><td>24</td><td>60</td><td>36</td><td>33</td><td>218</td></tr><tr><td>#4</td><td>05/10</td><td>68</td><td>25</td><td>63</td><td>37</td><td>33</td><td>226</td></tr></tbody></table></div>`)}
function teachersView(){return `<div class="tieu-de-trang"><div><h1>Giáo viên & phân quyền</h1><div class="mo-ta">Quản trị cấp cao quản lý quyền tạo đề, chấm bài và công bố kết quả.</div></div><button class="nut nut-chinh">+ Thêm giáo viên</button></div><div class="bang-wrap"><table class="bang"><thead><tr><th>Giáo viên</th><th>Email</th><th>Bài thi</th><th>Quyền</th></tr></thead><tbody><tr><td class="ten">Cô Lan</td><td>lan@g2gcareer.com</td><td>4</td><td>Tạo đề · Chấm · Công bố</td></tr><tr><td class="ten">Cô Mai</td><td>mai@g2gcareer.com</td><td>3</td><td>Tạo đề · Chấm</td></tr></tbody></table></div>`}
function trashView(){return `<div class="tieu-de-trang"><div><h1>Thùng rác</h1><div class="mo-ta">Chỉ Quản trị cấp cao nhìn thấy khu vực này.</div></div></div><div class="bang-wrap"><table class="bang"><thead><tr><th>Mục đã xóa</th><th>Người xóa</th><th>Thao tác</th></tr></thead><tbody><tr><td class="ten">TELC B1 – Đề 00</td><td>Cô Lan</td><td><div class="nhom-nut"><button class="nut nut-nho">Khôi phục</button><button class="nut nut-nho nut-nguy-hiem">Xóa vĩnh viễn</button></div></td></tr></tbody></table></div>`}
function bindAdmin(){const ne=document.getElementById('newExam');if(ne)ne.onclick=examBuilder;document.querySelectorAll('.editExam').forEach(b=>b.onclick=examBuilder);const rq=document.getElementById('requestGrade');if(rq)rq.onclick=()=>{S.requestSent=true;notify('Đã gửi yêu cầu xin chấm cho giáo viên tạo bài.');renderAdminMain()};const nq=document.getElementById('newQuestion');if(nq)nq.onclick=()=>questionBuilder();document.querySelectorAll('.editQuestion').forEach(b=>b.onclick=()=>questionBuilder(b.dataset.id));document.querySelectorAll('.previewQuestion').forEach(b=>b.onclick=()=>previewQuestion(b.dataset.id));if(S.adminTab==='grading')bindGrading();const mode=document.getElementById('gradeMode');if(mode)mode.onchange=e=>{S.gradeMode=e.target.value;renderAdminMain()};document.querySelectorAll('.scoreDetail').forEach(b=>b.onclick=scoreDetail);const ex=document.getElementById('exportScores');if(ex)ex.onclick=()=>notify('Bản dùng thật sẽ xuất tệp bảng điểm theo bộ lọc hiện tại.')}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="hop-thoai" id="modal"><div class="hop-thoai-box">${html}</div></div>`);document.querySelectorAll('.closeModal').forEach(b=>b.onclick=closeModal)}
function closeModal(){document.getElementById('modal')?.remove()}
function render(){if(!S.role){login();return}if(S.role==='student'){if(S.view==='studentResults')studentResults();else if(S.view==='exam')examView();else if(S.view==='submitted')submitted();else studentHome();return}if(S.view==='builder'){examBuilder();return}S.view='admin';admin()}
setInterval(()=>{if(S.view==='exam'&&S.time>0){S.time--;updateTimer()}},1000);
login();
})();