const API=String(globalThis.G2G_API_BASE||'/api').replace(/\/$/,'');
let pub={general:{systemName:'Thi thử tiếng Đức'},auth:{googleLoginEnabled:true},operations:{}},settings=null,infra=null,open=false,queued=false;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,{method='GET',body}={}){const r=await fetch(`${API}${path}`,{method,credentials:'include',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});let d={};try{d=await r.json();}catch{}if(!r.ok)throw new Error(d.error||`Lỗi ${r.status}`);return d;}
function master(){return document.querySelector('.thanh-dau .nhan')?.textContent?.trim()==='Quản trị cấp cao'&&Boolean(document.querySelector('.thanh-ben'));}
function student(){return document.querySelector('.thanh-dau .nhan')?.textContent?.trim()==='Học viên';}
function queue(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance();});}
function applyBrand(){const name=pub.general?.systemName||'Thi thử tiếng Đức';const h=document.querySelector('.ten-he-thong strong');if(h)h.textContent=name;document.title=`${name} · G2G`;}
function applyLogin(){const b=document.getElementById('googleLogin');if(!b)return;const on=pub.auth?.googleLoginEnabled!==false;b.disabled=!on;b.textContent=on?'Đăng nhập bằng Google':'Đăng nhập Google đang tạm tắt';}
function applyMaintenance(){document.querySelector('[data-g2g-maintenance]')?.remove();if(!student()||!pub.operations?.maintenanceMode)return;const h=document.querySelector('.thanh-dau');if(h){const x=document.createElement('div');x.dataset.g2gMaintenance='1';x.className='canh-bao-bao-tri';x.textContent=pub.operations.maintenanceMessage||'Hệ thống đang bảo trì.';h.insertAdjacentElement('afterend',x);}}
function inject(){const side=document.querySelector('.thanh-ben');if(!side||!master())return;let b=side.querySelector('[data-action="g2g-settings"]');if(!b){b=document.createElement('button');b.className='muc-ben';b.dataset.action='g2g-settings';b.textContent='Cài đặt';side.appendChild(b);}if(open){side.querySelectorAll('.muc-ben').forEach(x=>x.classList.remove('active'));b.classList.add('active');}}
function enhance(){applyBrand();applyLogin();applyMaintenance();inject();if(open&&master())render(false);if(open&&!master())open=false;}
function field(id,label,value,type='text',help=''){return `<label class="cai-dat-field"><span>${esc(label)}</span><input class="truong" id="${id}" type="${type}" value="${esc(value)}">${help?`<small>${esc(help)}</small>`:''}</label>`;}
function area(id,label,value,help=''){return `<label class="cai-dat-field"><span>${esc(label)}</span><textarea class="truong" id="${id}" rows="6">${esc(value)}</textarea>${help?`<small>${esc(help)}</small>`:''}</label>`;}
function toggle(id,label,on,help=''){return `<label class="cai-dat-toggle"><input id="${id}" type="checkbox" ${on?'checked':''}><span><b>${esc(label)}</b>${help?`<small>${esc(help)}</small>`:''}</span></label>`;}
function card(title,desc,body,extra=''){return `<section class="the cai-dat-card ${extra}"><div class="cai-dat-card-head"><h2>${esc(title)}</h2><p>${esc(desc)}</p></div><div class="cai-dat-fields">${body}</div></section>`;}
function val(id){return document.getElementById(id)?.value?.trim()||'';}function chk(id){return Boolean(document.getElementById(id)?.checked);}
async function loadPrivate(){const x=await api('/settings');settings=x.settings;infra=await api('/actions/getInfrastructureStatus',{method:'POST',body:{}});}
function form(){return {...settings,general:{...settings.general,systemName:val('sName'),organizationName:val('sOrg'),supportEmail:val('sSupport'),publicUrl:val('sUrl')},auth:{...settings.auth,googleLoginEnabled:chk('sGoogle'),allowNewStudents:chk('sSignup'),allowedDomain:val('sDomain').replace(/^@/,'').toLowerCase()},exam:{...settings.exam,allowRetake:chk('sRetake'),allowRestart:chk('sRestart')},smtp:{...settings.smtp,enabled:chk('sSmtp'),host:val('sHost'),port:Number(val('sPort')||587),security:val('sSecurity'),username:val('sUser'),fromName:val('sFromName'),fromEmail:val('sFrom'),replyTo:val('sReply'),timeoutMs:Number(val('sTimeout')||20000),rejectUnauthorized:chk('sTlsVerify')},email:{...settings.email,enabled:chk('sEmail'),resultSubject:val('sSubject'),resultText:document.getElementById('sText')?.value||'',resultHtml:document.getElementById('sHtml')?.value||''},operations:{...settings.operations,maintenanceMode:chk('sMaintenance'),maintenanceMessage:val('sMaintenanceText')}};}
function status(ok,a,b){return `<span class="tich-hop-status ${ok?'ok':'off'}">${ok?'●':'○'} ${esc(ok?a:b)}</span>`;}
function render(force=true){const target=document.querySelector('.noi-dung-quan-tri');if(!target||!master()||!settings)return;if(!force&&target.querySelector('.g2g-settings-page'))return;const s=settings;target.innerHTML=`<div class="g2g-settings-page"><div class="tieu-de-trang"><div><h1>Cài đặt hệ thống</h1><p>Toàn bộ cấu hình vận hành trên VPS. Chỉ Quản trị cấp cao được thay đổi.</p></div><div class="nhom-nut"><button class="nut" id="sRefresh">Kiểm tra kết nối</button><button class="nut chinh" id="sSave">Lưu cài đặt</button></div></div><div class="tich-hop-tong-quan"><div><b>Backend</b>${status(infra?.backend==='VPS','VPS hoạt động','Chưa kết nối')}</div><div><b>PostgreSQL</b>${status(Boolean(infra?.postgresql),'Hoạt động','Lỗi')}</div><div><b>Google Login</b>${status(Boolean(infra?.googleLoginConfigured),'Đã cấu hình','Thiếu Client ID/Secret')}</div><div><b>SMTP</b>${status(Boolean(infra?.smtp?.configured),'Sẵn sàng','Chưa hoàn tất')}</div></div><div class="cai-dat-grid">
${card('Thông tin hệ thống','Tên hiển thị và địa chỉ truy cập.',field('sName','Tên hệ thống',s.general.systemName)+field('sOrg','Đơn vị vận hành',s.general.organizationName)+field('sSupport','Email hỗ trợ',s.general.supportEmail,'email')+field('sUrl','Địa chỉ hệ thống',s.general.publicUrl,'url'))}
${card('Đăng nhập Google','Google OAuth chạy trực tiếp trên VPS, không cần Firebase.',toggle('sGoogle','Bật đăng nhập Google',s.auth.googleLoginEnabled)+toggle('sSignup','Cho học viên mới tự đăng ký',s.auth.allowNewStudents)+field('sDomain','Giới hạn tên miền email',s.auth.allowedDomain,'text','Để trống để nhận mọi tài khoản Google.'))}
${card('Máy chủ SMTP','SMTP riêng của anh. Mật khẩu được mã hóa trong PostgreSQL bằng khóa chỉ có trên VPS.',toggle('sSmtp','Bật SMTP',s.smtp.enabled)+field('sHost','SMTP Host',s.smtp.host)+field('sPort','Cổng SMTP',s.smtp.port,'number')+`<label class="cai-dat-field"><span>Bảo mật</span><select class="truong" id="sSecurity"><option value="starttls" ${s.smtp.security==='starttls'?'selected':''}>STARTTLS</option><option value="ssl" ${s.smtp.security==='ssl'?'selected':''}>SSL/TLS</option><option value="none" ${s.smtp.security==='none'?'selected':''}>Không mã hóa</option></select></label>`+field('sUser','Tên đăng nhập',s.smtp.username)+`<label class="cai-dat-field"><span>Mật khẩu / API key</span><div class="email-test"><input class="truong" id="sPassword" type="password" autocomplete="new-password" placeholder="Nhập khi cần cập nhật"><button class="nut" id="sSecret">Cập nhật mật khẩu</button></div><small>${infra?.smtp?.secretConfigured?'Đã lưu mật khẩu an toàn trên VPS.':'Chưa lưu mật khẩu SMTP.'}</small></label>`+field('sFromName','Tên người gửi',s.smtp.fromName)+field('sFrom','Email người gửi',s.smtp.fromEmail,'email')+field('sReply','Reply-To',s.smtp.replyTo,'email')+field('sTimeout','Timeout (ms)',s.smtp.timeoutMs,'number')+toggle('sTlsVerify','Kiểm tra chứng chỉ TLS',s.smtp.rejectUnauthorized!==false),'cai-dat-card-rong')}
${card('Email kết quả','Gửi khi giáo viên công bố kết quả.',toggle('sEmail','Bật email kết quả',s.email.enabled)+field('sSubject','Tiêu đề',s.email.resultSubject)+area('sText','Nội dung text',s.email.resultText,'Biến: {student}, {exam}, {score}, {result}, {url}')+area('sHtml','Nội dung HTML',s.email.resultHtml)+`<div class="email-test"><input class="truong" id="sTestTo" type="email" placeholder="Email nhận thử"><button class="nut" id="sTest">Gửi email thử</button></div>`,'cai-dat-card-rong')}
${card('Quyền làm bài','Điều khiển lượt thi của học viên.',toggle('sRetake','Cho phép thi lại',s.exam.allowRetake)+toggle('sRestart','Cho phép bỏ lượt đang làm để làm lại',s.exam.allowRestart))}
${card('Vận hành / bảo trì','Khóa bắt đầu lượt mới khi cần bảo trì.',toggle('sMaintenance','Bật chế độ bảo trì',s.operations.maintenanceMode)+field('sMaintenanceText','Thông báo bảo trì',s.operations.maintenanceMessage))}
</div><div class="cai-dat-footer"><span id="sState" class="phu-de">Mật khẩu SMTP không bao giờ được gửi lại xuống trình duyệt.</span><button class="nut chinh" id="sSaveBottom">Lưu cài đặt</button></div></div>`;bind();}
function state(msg,bad=false){const x=document.getElementById('sState');if(x){x.textContent=msg;x.classList.toggle('loi',bad);}}
async function save(){try{state('Đang lưu...');const out=await api('/actions/updateSystemSettings',{method:'POST',body:{settings:form()}});settings=out.settings;pub={general:settings.general,auth:settings.auth,operations:settings.operations};state('Đã lưu cài đặt.');applyBrand();applyLogin();}catch(e){state(e.message,true);}}
async function secret(){const password=document.getElementById('sPassword')?.value||'';if(!password)return state('Hãy nhập mật khẩu SMTP mới.',true);try{state('Đang mã hóa và lưu mật khẩu...');await api('/actions/updateSmtpSecret',{method:'POST',body:{password}});document.getElementById('sPassword').value='';infra=await api('/actions/getInfrastructureStatus',{method:'POST',body:{}});state('Đã cập nhật mật khẩu SMTP.');render(true);}catch(e){state(e.message,true);}}
async function test(){const to=val('sTestTo');if(!to)return state('Hãy nhập email nhận thử.',true);try{state('Đang gửi email thử...');await api('/actions/testSmtp',{method:'POST',body:{to}});state('Đã gửi email thử thành công.');}catch(e){state(e.message,true);}}
function bind(){document.getElementById('sSave')?.addEventListener('click',save);document.getElementById('sSaveBottom')?.addEventListener('click',save);document.getElementById('sSecret')?.addEventListener('click',secret);document.getElementById('sTest')?.addEventListener('click',test);document.getElementById('sRefresh')?.addEventListener('click',async()=>{try{infra=await api('/actions/getInfrastructureStatus',{method:'POST',body:{}});render(true);}catch(e){state(e.message,true);}});}
document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-action="g2g-settings"]');if(b){e.preventDefault();e.stopPropagation();open=true;try{await loadPrivate();render(true);}catch(err){console.error(err);}return;}if(e.target.closest?.('[data-action="admin-tab"]'))open=false;},true);
new MutationObserver(queue).observe(document.getElementById('app'),{childList:true,subtree:true});
(async()=>{try{pub=await api('/public-settings');}catch{}queue();})();
